<a href="https://colab.research.google.com/github/luisabernals-oss/programacion-P1/blob/main/conectar_base.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pymysql pandas

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 1.2 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [2]:
import pymysql
import pandas as pd

connection = pymysql.connect(
    host="relational.fel.cvut.cz",
    port=3306,
    user="guest",
    password="ctu-relational",
    database="restbase"
)

print("Conectado!")

Conectado!

In [ ]:
query = "SHOW TABLES"
tables = pd.read_sql(query, connection)
tables

/tmp/ipykernel_6711/1992093721.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tables = pd.read_sql(query, connection)

  Tables_in_restbase
0        generalinfo
1         geographic
2           location

In [ ]:
query = "SELECT * FROM location"
df = pd.read_sql(query, connection)

df.to_csv("tabla.csv", index=False)
df.head()

/tmp/ipykernel_6711/1140612496.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

   id_restaurant  street_num        street_name           city
0              1       242.0          church st  san francisco
1              2       135.0     el camino real     san carlos
2              3       430.0           broadway  san francisco
3              4      1103.0  e. el camino real      sunnyvale
4              5       833.0  w. el camino real      sunnyvale

## variables

In [ ]:
query = "SHOW TABLES"
tables = pd.read_sql(query, connection)

tables

/tmp/ipykernel_6711/3893829325.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  tables = pd.read_sql(query, connection)

  Tables_in_restbase
0        generalinfo
1         geographic
2           location

In [ ]:
table_list = tables.iloc[:,0].tolist()
table_list

['generalinfo', 'geographic', 'location']

In [ ]:
for table in table_list:
    print("\nTabla:", table)

    query = f"DESCRIBE {table}"
    df = pd.read_sql(query, connection)

    display(df)

/tmp/ipykernel_6711/1202941598.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

Tabla: generalinfo

           Field          Type Null  Key Default Extra
0  id_restaurant       int(11)   NO  PRI    None
1          label  varchar(255)  YES         None
2      food_type  varchar(255)  YES         None
3           city  varchar(255)  YES  MUL    None
4         review  decimal(2,1)  YES         None

Tabla: geographic

/tmp/ipykernel_6711/1202941598.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

    Field          Type Null  Key Default Extra
0    city  varchar(255)   NO  PRI    None
1  county  varchar(255)  YES         None
2  region  varchar(255)  YES         None

Tabla: location

/tmp/ipykernel_6711/1202941598.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

           Field          Type Null  Key Default Extra
0  id_restaurant       int(11)   NO  PRI    None
1     street_num       int(11)  YES         None
2    street_name  varchar(255)  YES         None
3           city  varchar(255)  YES  MUL    None

## ver datos

In [ ]:
query = "SELECT * FROM generalinfo LIMIT 10"
df = pd.read_sql(query, connection)

df

/tmp/ipykernel_6711/3467504048.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

,id_restaurant,label,food_type,city,review
0,1,sparky's diner,24 hour diner,san francisco,2.3
1,2,kabul afghan cuisine,afghani,san carlos,3.8
2,3,helmand restaurant,afghani,san francisco,4.0
3,4,afghani house,afghani,sunnyvale,3.6
4,5,kabul afghan cusine,afghani,sunnyvale,3.7
5,6,bamyan afghan restaurant,afghani,san rafael,2.8
6,7,kabul palace,afghani,san jose,2.8
7,8,kandahar,afghani,concord,3.5
8,9,kabobs house,afghani,vacaville,2.7
9,10,massawa restaurant,african,san francisco,3.4

In [ ]:
tables = ["generalinfo", "geographic", "location"]

for table in tables:
    print("\nDatos de la tabla:", table)

    query = f"SELECT * FROM {table} LIMIT 5"
    df = pd.read_sql(query, connection)

    display(df)

/tmp/ipykernel_6711/33771661.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

Datos de la tabla: generalinfo

   id_restaurant                 label      food_type           city  review
0              1        sparky's diner  24 hour diner  san francisco     2.3
1              2  kabul afghan cuisine        afghani     san carlos     3.8
2              3    helmand restaurant        afghani  san francisco     4.0
3              4         afghani house        afghani      sunnyvale     3.6
4              5   kabul afghan cusine        afghani      sunnyvale     3.7

Datos de la tabla: geographic

/tmp/ipykernel_6711/33771661.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

              city               county    region
0          alameda       alameda county  bay area
1            alamo  contra costa county  bay area
2           albany       alameda county  bay area
3           alviso   santa clara county  bay area
4  american canyon              unknown  bay area

Datos de la tabla: location

/tmp/ipykernel_6711/33771661.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

   id_restaurant  street_num        street_name           city
0              1         242          church st  san francisco
1              2         135     el camino real     san carlos
2              3         430           broadway  san francisco
3              4        1103  e. el camino real      sunnyvale
4              5         833  w. el camino real      sunnyvale

In [ ]:
generalinfo = pd.read_sql("SELECT * FROM generalinfo", connection)
geographic = pd.read_sql("SELECT * FROM geographic", connection)
location = pd.read_sql("SELECT * FROM location", connection)

/tmp/ipykernel_6711/2843710696.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  generalinfo = pd.read_sql("SELECT * FROM generalinfo", connection)
/tmp/ipykernel_6711/2843710696.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  geographic = pd.read_sql("SELECT * FROM geographic", connection)
/tmp/ipykernel_6711/2843710696.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  location = pd.read_sql("SELECT * FROM location", connection)

In [ ]:
generalinfo.head()
geographic.head()
location.head()

   id_restaurant  street_num        street_name           city
0              1       242.0          church st  san francisco
1              2       135.0     el camino real     san carlos
2              3       430.0           broadway  san francisco
3              4      1103.0  e. el camino real      sunnyvale
4              5       833.0  w. el camino real      sunnyvale

In [ ]:
## join




import pandas as pd

generalinfo = pd.read_sql("SELECT * FROM generalinfo", connection)
geographic = pd.read_sql("SELECT * FROM geographic", connection)
location = pd.read_sql("SELECT * FROM location", connection)

/tmp/ipykernel_6711/1878947171.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  generalinfo = pd.read_sql("SELECT * FROM generalinfo", connection)
/tmp/ipykernel_6711/1878947171.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  geographic = pd.read_sql("SELECT * FROM geographic", connection)
/tmp/ipykernel_6711/1878947171.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  location = pd.read_sql("SELECT * FROM location", connection)

In [ ]:
data = generalinfo.merge(geographic, on="placeID") \
                  .merge(location, on="placeID")

KeyError: 'placeID'

In [ ]:
query = """
SELECT *
FROM consumer c
JOIN rating r ON c.consumer_id = r.consumer_id
JOIN restaurant t ON r.restaurant_id = t.restaurant_id
LIMIT 100
"""

df = pd.read_sql(query, connection)

/tmp/ipykernel_6711/1518767378.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

DatabaseError: Execution failed on sql '
SELECT *
FROM consumer c
JOIN rating r ON c.consumer_id = r.consumer_id
JOIN restaurant t ON r.restaurant_id = t.restaurant_id
LIMIT 100
': (1146, "Table 'restbase.consumer' doesn't exist")